/**
 * Generate per-realm docker-compose.yml content.
 *
 * Each realm gets a single worldserver service using a shared Docker image.
 * No build stanza — the image is pre-built by the global build pipeline.
 * Realm data (etc, logs) lives on the host filesystem at REALM_HOST_DIR/{id}/.
 */

import { charDb, worldDb } from "./db-realm";
import { DEFAULT_BRANDING } from "./branding";
import { readSettings } from "./settings";
import { type RealmManifest, resolveEnvPlaceholders } from "./manifest";

/** World port offset: realm 1 = 8085, realm 2 = 8086, etc. */
export function worldPort(realmId: number): number {
  return 8085 + realmId - 1;
}

/** RA port offset: realm 1 = 3443, realm 2 = 3444, etc. */
export function raPort(realmId: number): number {
  return 3443 + realmId - 1;
}

/** SOAP port offset: realm 1 = 7878, realm 2 = 7879, etc. */
export function soapPort(realmId: number): number {
  return 7878 + realmId - 1;
}

/** DB-import image tag derived from worldserver image tag. */
export function dbImportImageTag(worldserverTag: string): string {
  return worldserverTag.replace("ac-worldserver:", "ac-db-import:");
}

export interface RealmComposePaths {
  configPath: string;
  dataPath: string;
  logsPath: string;
}

const DEFAULT_PATHS: RealmComposePaths = {
  configPath: "/azerothcore/env/dist/etc",
  dataPath: "/azerothcore/env/dist/data",
  logsPath: "/azerothcore/env/dist/logs",
};

/** Extra manifest-derived environment variables to inject into compose services. */
export interface ManifestEnv {
  worldserver?: Record<string, string>;
  dbImport?: Record<string, string>;
}

/** Build a ManifestEnv from a RealmManifest for a given realm, resolving placeholders. */
export function buildManifestEnv(
  manifest: RealmManifest | null | undefined,
  realmId: number,
  sourceId: string
): ManifestEnv {
  if (!manifest?.environment) return {};
  const dbHost = process.env.DB_HOST ?? "ac-database";
  const dbPort = process.env.DB_PORT ?? "3306";
  const settings = readSettings();
  const dbPass = settings.db.rootPassword;
  const ctx = { realmId, dbHost, dbPort, dbPass, sourceId };
  return {
    worldserver: manifest.environment.worldserver
      ? resolveEnvPlaceholders(manifest.environment.worldserver, ctx)
      : undefined,
    dbImport: manifest.environment.dbImport
      ? resolveEnvPlaceholders(manifest.environment.dbImport, ctx)
      : undefined,
  };
}

/**
 * Generate a per-realm docker-compose.yml.
 * @param realmId — the realm's DB ID
 * @param imageTag — the full Docker image reference (e.g. "ac-worldserver:azerothcore-wotlk-20260408-120000")
 * @param paths — container paths from the source config (optional, defaults to AzerothCore paths)
 * @param manifestEnv — extra env vars from the source manifest (resolved placeholders)
 */
export function generateRealmCompose(
  realmId: number,
  imageTag: string,
  paths?: Partial<RealmComposePaths>,
  manifestEnv?: ManifestEnv,
): string {
  const settings = readSettings();
  const dbHost = process.env.DB_HOST ?? "ac-database";
  const dbPort = process.env.DB_PORT ?? "3306";
  const dbRootPass = settings.db.rootPassword;
  const composeProject = process.env.COMPOSE_PROJECT ?? "realmmanager";
  const hostDir = process.env.REALM_HOST_DIR ?? "./data/realms";
  const charDatabase = charDb(realmId);
  const worldDatabase = worldDb(realmId);
  const wPort = worldPort(realmId);
  const rPort = raPort(realmId);
  const sPort = soapPort(realmId);
  const dbImportTag = dbImportImageTag(imageTag);
  const p = { ...DEFAULT_PATHS, ...paths };

  // Build extra env var YAML lines for injection into services
  // Escape double quotes in values to keep YAML valid
  const escapeYamlValue = (v: string) => v.replace(/"/g, '\\"');
  const extraWsEnv = manifestEnv?.worldserver ?? {};
  const extraDbImportEnv = manifestEnv?.dbImport ?? {};
  const wsEnvLines = Object.entries(extraWsEnv)
    .map(([k, v]) => `      ${k}: "${escapeYamlValue(v)}"`)
    .join("\n");
  const dbImportEnvLines = Object.entries(extraDbImportEnv)
    .map(([k, v]) => `      ${k}: "${escapeYamlValue(v)}"`)
    .join("\n");

  const realmHostDir = `${hostDir}/${realmId}`;
  const etcHostDir = `${realmHostDir}/etc`;
  const logsHostDir = `${realmHostDir}/logs`;

  const clientDataImage = process.env.AC_CLIENT_DATA_IMAGE ?? "acore/ac-wotlk-client-data:master";

  return `# Realm ${realmId} — auto-generated by ${DEFAULT_BRANDING.serverName}
# DO NOT edit manually — regenerated on build change

services:
  ac-client-data-init-${realmId}:
    container_name: ac-client-data-init-${realmId}
    image: ${clientDataImage}
    volumes:
      - ac-client-data:${p.dataPath}

  ac-db-import-${realmId}:
    container_name: ac-db-import-${realmId}
    image: ${dbImportTag}
    networks:
      - ac-network
    user: root
    environment:
      AC_DATA_DIR: "${p.dataPath}"
      AC_LOGS_DIR: "${p.logsPath}"
      AC_LOGIN_DATABASE_INFO: "${dbHost};${dbPort};root;${dbRootPass};acore_auth"
      AC_WORLD_DATABASE_INFO: "${dbHost};${dbPort};root;${dbRootPass};${worldDatabase}"
      AC_CHARACTER_DATABASE_INFO: "${dbHost};${dbPort};root;${dbRootPass};${charDatabase}"${dbImportEnvLines ? `\n${dbImportEnvLines}` : ""}
    volumes:
      - ${etcHostDir}:${p.configPath}
      - ${logsHostDir}:${p.logsPath}:delegated

  ac-worldserver-${realmId}:
    container_name: ac-worldserver-${realmId}
    image: ${imageTag}
    networks:
      - ac-network
    stdin_open: true
    tty: true
    restart: unless-stopped
    user: root
    depends_on:
      ac-client-data-init-${realmId}:
        condition: service_completed_successfully
      ac-db-import-${realmId}:
        condition: service_completed_successfully
    environment:
      AC_DATA_DIR: "${p.dataPath}"
      AC_LOGS_DIR: "${p.logsPath}"
      AC_REALM_ID: "${realmId}"
      AC_WORLD_SERVER_PORT: "8085"
      AC_BIND_IP: "0.0.0.0"
      AC_LOGIN_DATABASE_INFO: "${dbHost};${dbPort};root;${dbRootPass};acore_auth"
      AC_WORLD_DATABASE_INFO: "${dbHost};${dbPort};root;${dbRootPass};${worldDatabase}"
      AC_CHARACTER_DATABASE_INFO: "${dbHost};${dbPort};root;${dbRootPass};${charDatabase}"
      AC_UPDATES_ENABLE_DATABASES: "0"
      AC_DISABLE_INTERACTIVE: "1"
      AC_CLOSE_IDLE_CONNECTIONS: "0"
      AC_RA_ENABLE: "1"
      AC_RA_IP: "0.0.0.0"
      AC_SOAP_ENABLED: "1"
      AC_SOAP_IP: "0.0.0.0"${wsEnvLines ? `\n${wsEnvLines}` : ""}
    ports:
      - "${wPort}:8085"
      - "${sPort}:7878"
      - "${rPort}:3443"
    volumes:
      - ac-client-data:${p.dataPath}:ro
      - ${etcHostDir}:${p.configPath}
      - ${logsHostDir}:${p.logsPath}:delegated

volumes:
  ac-client-data:
    name: ${composeProject}_ac-client-data

networks:
  ac-network:
    external: true
    name: ${composeProject}_ac-network
`;
}
